#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  5 23:32:21 2023

@author: yoavharlap
"""
from aspire.volume import Volume

import matplotlib.pyplot as plt
import numpy as np


import mrcfile
mrc = mrcfile.open("/scratch/amitayeldar/dataForTamir/Relion10028Contaminated/particles.mrcs",'r')
#mrc = Volume.load("/scratch/amitayeldar/dataForTamir/Relion10028Contaminated/particles.mrcs", dtype=np.float64)
#mrc = Volume.load(mrc,dtype="float32")

outliers_imgs = np.array(mrc.data)
mrc.close()


for i in range(3):
    plt.imshow(outliers_imgs[i])
    plt.show()
    
